version: "2"

services:
  broker:
    image: "rabbitmq:3-management"
    container_name: broker
    ports:
      - "15672:15672"
      - "5672:5672"

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - "1024:80"
    depends_on:
      - "broker"
    restart: always
    env_file:
      - .${target}.env

  reporting:
    container_name: reporting
    build:
      context: .
      dockerfile: ./cmd/reporting/Dockerfile
    depends_on:
      - "broker"
    restart: always
    env_file:
      - .${target}.env
